version: '3'
services:
  frontend:
    image: ikapata/day_to_day_planner_frontend
    ports:
      - "3000:3000"
    container_name: frontend
    environment:
      - BACKEND_URL=http://backend:8080
    restart: always
    links:
      - backend
  backend:
    image: ikapata/day_to_day_planner_backend
    ports:
      - "8080:8080"
    container_name: backend
    links:
      - db
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/daytodayplanner
      - SPRING_DATASOURCE_USERNAME=daytodayplanner
      - SPRING_DATASOURCE_PASSWORD=daytodayplanner
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  
  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    container_name: db
    restart: always
    volumes:
      - daytodaydata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=daytodayplanner
      - POSTGRES_PASSWORD=daytodayplanner
      - POSTGRES_DB=daytodayplanner

volumes:
  daytodaydata:
