name: backend-ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f ./backend/day-by-day-planner/pom.xml test
  
  docker: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push register app
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./backend/day-by-day-planner/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/day_to_day_planner_backend:latest
