name: backend-ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push register app
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./frontend/day-to-day-planner
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/day_to_day_planner_frontend:latest
